// Create a User
POST http://localhost:5000/users
Content-Type: application/json

{
    "namauser":"Admin",
    "username":"admin@tpp.com",
    "password":"Tpp123@",
    "confPassword": "Tpp123@",
    "role":"pranata komputer"
}

###
// get All User
GET http://localhost:5000/pegawais

###
// get ById User
GET http://localhost:5000/users/c36b8b23-ad2a-443a-a865-e2ecdd1a3e12

###
// get absen
GET http://localhost:5000/repotabsen/1&2023

###
// update a User
PATCH http://localhost:5000/users/c36b8b23-ad2a-443a-a865-e2ecdd1a3e12
Content-Type: application/json

{
    "namauser":"Hazuna Akihako",
    "username":"hazuna@tpp.com",
    "password":"123@2023",
    "confPassword": "123@2023",
    "role":"DataEntry"
}

###
// Delete a User
DELETE http://localhost:5000/users/c36b8b23-ad2a-443a-a865-e2ecdd1a3e12

###
// Login
POST http://18.222.216.165:5000/login
Content-Type: application/json

{
    "username":"admin@tpp.com",
    "password":"Tpp123@"
}

###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"putri@tpp.com",
    "password":"putri@2023"
}

###
// Me
GET http://localhost:5000/me

###
// logout
DELETE http://localhost:5000/logout